package websocket

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/gbrlsnchs/jwt/v3"
	"github.com/google/uuid"
	gws "github.com/gorilla/websocket"
	"github.com/pterodactyl/wings/config"
	"github.com/pterodactyl/wings/remote"
	"github.com/pterodactyl/wings/router/tokens"
	"github.com/pterodactyl/wings/server"
	"github.com/reearth/ygo/crdt"
	"github.com/stretchr/testify/require"
)

// Generated by yjs@13.6.30 using Y.encodeStateAsUpdate on Y.Text("content").
const nativeFileCollabYjsFixture = "AQHZqLZjAAQBB2NvbnRlbnQWYnJvd3NlciDwn5iACnNlbGVjdGlvbgA="

func nativeFileCollabTestPeer(t *testing.T, state []byte) (*crdt.Doc, *crdt.YText) {
	t.Helper()
	doc := crdt.New()
	text := doc.GetText("content")
	require.NoError(t, crdt.ApplyUpdateV1(doc, state, "test-sync"))
	return doc, text
}

func nativeFileCollabTestInsert(t *testing.T, doc *crdt.Doc, text *crdt.YText, stateVector crdt.StateVector, index int, value string) []byte {
	t.Helper()
	doc.Transact(func(transaction *crdt.Transaction) {
		text.Insert(transaction, index, value, nil)
	})
	return crdt.EncodeStateAsUpdateV1(doc, stateVector)
}

func TestNativeFileCollabUsesWingsRsWireEvents(t *testing.T) {
	require.True(t, NativeFileCollaborationEnabled)
	require.True(t, IsNativeFileCollaborationEvent(FileCollabSubscribeEvent))
	require.True(t, IsNativeFileCollaborationEvent(FileCollabUpdateEvent))
	require.True(t, IsNativeFileCollaborationEvent(FileCollabAwarenessEvent))
	require.False(t, IsNativeFileCollaborationEvent(fileCollabSyncEvent))
	require.False(t, IsNativeFileCollaborationEvent(BetterFilesCollabPatchEvent))
}

func TestNativeFileCollabValidatesExactPositionalArguments(t *testing.T) {
	require.True(t, nativeFileCollabValidArgs(Message{Event: FileCollabSubscribeEvent, Args: []string{"/file.txt"}}))
	require.True(t, nativeFileCollabValidArgs(Message{Event: FileCollabUpdateEvent, Args: []string{"/file.txt", "1", "AQ=="}}))
	require.True(t, nativeFileCollabValidArgs(Message{Event: FileCollabAwarenessEvent, Args: []string{"/file.txt", "AQ=="}}))
	require.False(t, nativeFileCollabValidArgs(Message{Event: FileCollabSaveEvent, Args: []string{"/file.txt", "unexpected-content"}}))
	require.False(t, nativeFileCollabValidArgs(Message{Event: FileCollabUpdateEvent, Args: []string{"/file.txt", "2", "AQ=="}}))
	require.False(t, nativeFileCollabValidArgs(Message{Event: FileCollabAwarenessEvent, Args: []string{"/file.txt", ""}}))
}

func nativeFileCollabTestServer(t *testing.T, serverUUID string) *server.Server {
	t.Helper()
	root := t.TempDir()
	next, err := config.NewAtPath(filepath.Join(root, "config.yml"))
	require.NoError(t, err)
	next.AuthenticationToken = "native-collaboration-test-token"
	next.System.Data = filepath.Join(root, "volumes")
	next.System.User.Uid = os.Getuid()
	next.System.User.Gid = os.Getgid()
	next.System.FileHistory.Enabled = false
	config.Set(next)

	settings, err := json.Marshal(map[string]any{
		"uuid":      serverUUID,
		"build":     map[string]any{"disk_space": 100},
		"container": map[string]any{"image": "alpine:3.20"},
	})
	require.NoError(t, err)
	manager := server.NewEmptyManager(nil)
	s, err := manager.InitServer(remote.ServerConfigurationResponse{Settings: settings})
	require.NoError(t, err)
	t.Cleanup(s.CtxCancel)
	return s
}

func nativeFileCollabTestSocket(t *testing.T) (*gws.Conn, *gws.Conn) {
	t.Helper()
	serverConn := make(chan *gws.Conn, 1)
	httpServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		conn, err := (&gws.Upgrader{CheckOrigin: func(*http.Request) bool { return true }}).Upgrade(w, r, nil)
		if err != nil {
			return
		}
		serverConn <- conn
	}))
	t.Cleanup(httpServer.Close)

	u, err := url.Parse(httpServer.URL)
	require.NoError(t, err)
	u.Scheme = "ws"
	client, _, err := gws.DefaultDialer.Dial(u.String(), nil)
	require.NoError(t, err)
	serverSide := <-serverConn
	t.Cleanup(func() {
		_ = client.Close()
		_ = serverSide.Close()
	})
	return serverSide, client
}

func nativeFileCollabTestHandler(t *testing.T, s *server.Server, user string) (*Handler, *gws.Conn, context.Context) {
	t.Helper()
	serverSide, client := nativeFileCollabTestSocket(t)
	// NumericDate has second precision; move issuance to the next second so it
	// cannot compare before the package boot timestamp due to truncation.
	now := time.Now().Add(time.Second)
	h := &Handler{
		Connection: serverSide,
		server:     s,
		uuid:       uuid.New(),
		limiter:    NewLimiter(),
		jwt: &tokens.WebsocketPayload{
			Payload: jwt.Payload{
				IssuedAt:       jwt.NumericDate(now),
				ExpirationTime: jwt.NumericDate(now.Add(time.Hour)),
			},
			Scoped:      tokens.Scoped{Scope: string(tokens.Websocket)},
			UserUUID:    user,
			UserName:    user,
			ServerUUID:  s.ID(),
			Permissions: []string{PermissionConnect, betterFilesCollabReadPermission, betterFilesCollabWritePermission},
		},
	}
	ctx, cancel := context.WithCancel(context.Background())
	t.Cleanup(cancel)
	return h, client, ctx
}

func nativeFileCollabReadMessage(t *testing.T, conn *gws.Conn) Message {
	t.Helper()
	require.NoError(t, conn.SetReadDeadline(time.Now().Add(2*time.Second)))
	defer conn.SetReadDeadline(time.Time{})
	var message Message
	require.NoError(t, conn.ReadJSON(&message))
	return message
}

func nativeFileCollabRequireEvent(t *testing.T, conn *gws.Conn, event Event, argCount int) Message {
	t.Helper()
	message := nativeFileCollabReadMessage(t, conn)
	require.Equal(t, event, message.Event, "unexpected websocket message args: %v", message.Args)
	require.Len(t, message.Args, argCount)
	return message
}

func TestNativeFileCollabWebsocketFlow(t *testing.T) {
	const (
		serverUUID = "11111111-1111-1111-1111-111111111111"
		path       = "/config.txt"
		otherPath  = "/other.txt"
	)
	s := nativeFileCollabTestServer(t, serverUUID)
	require.NoError(t, os.WriteFile(filepath.Join(s.Filesystem().Path(), "config.txt"), []byte("hello"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(s.Filesystem().Path(), "other.txt"), []byte("isolated"), 0o644))

	sender, senderConn, senderCtx := nativeFileCollabTestHandler(t, s, "sender")
	recipient, recipientConn, recipientCtx := nativeFileCollabTestHandler(t, s, "recipient")
	isolated, isolatedConn, isolatedCtx := nativeFileCollabTestHandler(t, s, "isolated")

	require.NoError(t, sender.HandleInbound(senderCtx, Message{Event: FileCollabSubscribeEvent, Args: []string{path}}))
	syncMessage := nativeFileCollabRequireEvent(t, senderConn, fileCollabSyncEvent, 3)
	require.Equal(t, path, syncMessage.Args[0])
	require.JSONEq(t, `{"dirty":false}`, syncMessage.Args[2])
	nativeFileCollabRequireEvent(t, senderConn, fileCollabParticipantsEvent, 2)

	require.NoError(t, recipient.HandleInbound(recipientCtx, Message{Event: FileCollabSubscribeEvent, Args: []string{path}}))
	nativeFileCollabRequireEvent(t, recipientConn, fileCollabSyncEvent, 3)
	nativeFileCollabRequireEvent(t, senderConn, fileCollabParticipantsEvent, 2)
	participants := nativeFileCollabRequireEvent(t, recipientConn, fileCollabParticipantsEvent, 2)
	var participantList []nativeFileCollabParticipant
	require.NoError(t, json.Unmarshal([]byte(participants.Args[1]), &participantList))
	require.Len(t, participantList, 2)

	require.NoError(t, isolated.HandleInbound(isolatedCtx, Message{Event: FileCollabSubscribeEvent, Args: []string{otherPath}}))
	nativeFileCollabRequireEvent(t, isolatedConn, fileCollabSyncEvent, 3)
	nativeFileCollabRequireEvent(t, isolatedConn, fileCollabParticipantsEvent, 2)

	initialState, err := base64.StdEncoding.DecodeString(syncMessage.Args[1])
	require.NoError(t, err)
	browser, browserText := nativeFileCollabTestPeer(t, initialState)
	defer browser.Destroy()
	vector := browser.StateVector()
	update := nativeFileCollabTestInsert(t, browser, browserText, vector, browserText.Len(), " world")
	split := len(update) / 2
	require.Greater(t, split, 0)

	require.NoError(t, sender.HandleInbound(senderCtx, Message{Event: FileCollabUpdateEvent, Args: []string{
		path, "0", base64.StdEncoding.EncodeToString(update[:split]),
	}}))
	session := nativeFileCollabRegistry.sessions[nativeFileCollabKey(serverUUID, path)]
	require.NotNil(t, session)
	require.Equal(t, "hello", session.text.ToString(), "an incomplete chunk must not mutate the document")

	require.NoError(t, sender.HandleInbound(senderCtx, Message{Event: FileCollabUpdateEvent, Args: []string{
		path, "1", base64.StdEncoding.EncodeToString(update[split:]),
	}}))
	updateMessage := nativeFileCollabRequireEvent(t, recipientConn, FileCollabUpdateEvent, 2)
	require.Equal(t, path, updateMessage.Args[0])
	require.Equal(t, base64.StdEncoding.EncodeToString(update), updateMessage.Args[1])
	require.Equal(t, "hello world", session.text.ToString())

	require.NoError(t, sender.HandleInbound(senderCtx, Message{Event: FileCollabAwarenessEvent, Args: []string{path, "not-base64"}}))
	awarenessError := nativeFileCollabRequireEvent(t, senderConn, fileCollabErrorEvent, 2)
	require.Equal(t, path, awarenessError.Args[0])
	require.Equal(t, "invalid awareness update", awarenessError.Args[1])

	awareness := base64.StdEncoding.EncodeToString([]byte{1, 2, 3, 4})
	require.NoError(t, sender.HandleInbound(senderCtx, Message{Event: FileCollabAwarenessEvent, Args: []string{path, awareness}}))
	awarenessMessage := nativeFileCollabRequireEvent(t, recipientConn, FileCollabAwarenessEvent, 2)
	require.Equal(t, []string{path, awareness}, awarenessMessage.Args)

	require.NoError(t, sender.HandleInbound(senderCtx, Message{Event: FileCollabSaveEvent, Args: []string{path}}))
	senderSaved := nativeFileCollabRequireEvent(t, senderConn, fileCollabSavedEvent, 2)
	recipientSaved := nativeFileCollabRequireEvent(t, recipientConn, fileCollabSavedEvent, 2)
	require.Equal(t, senderSaved.Args, recipientSaved.Args)
	require.Equal(t, path, senderSaved.Args[0])
	savedContent, err := os.ReadFile(filepath.Join(s.Filesystem().Path(), "config.txt"))
	require.NoError(t, err)
	require.Equal(t, "hello world", string(savedContent))

	require.NoError(t, sender.HandleInbound(senderCtx, Message{Event: FileCollabUnsubscribeEvent, Args: []string{path}}))
	remaining := nativeFileCollabRequireEvent(t, recipientConn, fileCollabParticipantsEvent, 2)
	require.JSONEq(t, `[{"user":"recipient","name":"recipient","avatar":null}]`, remaining.Args[1])

	require.NotEqual(t, nativeFileCollabKey(serverUUID, path), nativeFileCollabKey("other-server", path))
	require.NotEqual(t, nativeFileCollabKey(serverUUID, path), nativeFileCollabKey(serverUUID, otherPath))
	require.NoError(t, isolatedConn.SetReadDeadline(time.Now().Add(100*time.Millisecond)))
	var unexpected Message
	require.Error(t, isolatedConn.ReadJSON(&unexpected), "a different file session must receive no collaboration broadcasts")
}

func TestNativeFileCollabYjsFullStateRoundTrip(t *testing.T) {
	session := nativeFileCollabNewSession("server", "/config.yml", "hello 😀\nworld")
	state := session.doc.EncodeStateAsUpdate()
	peer, peerText := nativeFileCollabTestPeer(t, state)
	defer peer.Destroy()

	require.Equal(t, "hello 😀\nworld", peerText.ToString())
	require.Equal(t, "hello 😀\nworld", session.text.ToString())
}

func TestNativeFileCollabAppliesBrowserYjsV1Update(t *testing.T) {
	session := nativeFileCollabNewSession("server", "/config.yml", "")
	update, err := base64.StdEncoding.DecodeString(nativeFileCollabYjsFixture)
	require.NoError(t, err)

	resync, err := session.applyUpdate(update, "browser")
	require.NoError(t, err)
	require.False(t, resync)
	require.Equal(t, "browser 😀\nselection", session.text.ToString())
}

func TestNativeFileCollabConcurrentYjsUpdatesConverge(t *testing.T) {
	session := nativeFileCollabNewSession("server", "/config.yml", "ab")
	initialState := session.doc.EncodeStateAsUpdate()
	initialVector := session.doc.StateVector()

	peerA, textA := nativeFileCollabTestPeer(t, initialState)
	defer peerA.Destroy()
	peerB, textB := nativeFileCollabTestPeer(t, initialState)
	defer peerB.Destroy()

	updateA := nativeFileCollabTestInsert(t, peerA, textA, initialVector, 1, "😀")
	updateB := nativeFileCollabTestInsert(t, peerB, textB, initialVector, 1, "Y\nZ")

	_, err := session.applyUpdate(updateA, "peer-a")
	require.NoError(t, err)
	_, err = session.applyUpdate(updateB, "peer-b")
	require.NoError(t, err)
	require.NoError(t, crdt.ApplyUpdateV1(peerA, updateB, "peer-b"))
	require.NoError(t, crdt.ApplyUpdateV1(peerB, updateA, "peer-a"))

	require.Equal(t, session.text.ToString(), textA.ToString())
	require.Equal(t, session.text.ToString(), textB.ToString())
}

func TestNativeFileCollabCompactionRequestsResyncWithoutChangingContent(t *testing.T) {
	session := nativeFileCollabNewSession("server", "/config.yml", "before")
	peer, peerText := nativeFileCollabTestPeer(t, session.doc.EncodeStateAsUpdate())
	defer peer.Destroy()
	vector := session.doc.StateVector()
	update := nativeFileCollabTestInsert(t, peer, peerText, vector, peerText.Len(), " after")

	session.appliedUpdateBytes = fileCollabCompactionUpdateBytes
	resync, err := session.applyUpdate(update, "peer")
	require.NoError(t, err)
	require.True(t, resync)
	require.Equal(t, "before after", session.text.ToString())
	require.Zero(t, session.appliedUpdateBytes)
}

func TestNativeFileCollabRejectsMalformedYjsUpdate(t *testing.T) {
	session := nativeFileCollabNewSession("server", "/config.yml", "before")
	resync, err := session.applyUpdate([]byte("not a yjs update"), "peer")
	require.Error(t, err)
	require.False(t, resync)
	require.Equal(t, "before", session.text.ToString())
}

func TestNativeFileCollabParticipantMatchesWingsRsShape(t *testing.T) {
	avatar := "https://panel.example/avatar.png"
	payload, err := json.Marshal([]nativeFileCollabParticipant{{
		User:   "user-uuid",
		Name:   "Panel User",
		Avatar: &avatar,
	}})
	require.NoError(t, err)
	require.JSONEq(t, `[{"user":"user-uuid","name":"Panel User","avatar":"https://panel.example/avatar.png"}]`, string(payload))
}

func TestNativeFileCollabTruncateUTF8KeepsValidBoundary(t *testing.T) {
	content := "ab😀cd"
	truncated := nativeFileCollabTruncateUTF8(content, 5)
	require.Equal(t, "ab", truncated)
}
